version: '2.1'

services:
  db:
    container_name: db
    build: ./db
    ports:
        - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  app:
    container_name: app
    build: ./
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=app.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/si_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/si_test
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      app:
        condition: service_started
      # client:
      #   condition: service_started
    links:
      - app
      # - client

  # client:
  #   container_name: client
  #   build:
  #     context: https://github.com/bin4ryio/app-microservices-client.git
  #     args:
  #       - NODE_ENV=development
  #       - CLIENT_APP_URL=${CLIENT_APP_URL}
  #   ports:
  #     - '9000:9000' # expose ports - HOST:CONTAINER
  #   depends_on:
  #     app:
  #       condition: service_started
  #   links:
  #     - app
